### PR TITLE
Jt 26 add spring security

### PR DESCRIPTION
**Pull request by freesky15**
Add spring security(jwt support)

### CODE REVIEW

**Comment by pelmegov** [comment]
@freesky15 @saffchen what is a difference between the similar opened PR?

**Comment by saffchen** [comment]
> what is a difference between the similar opened PR?

This functionality is required in front to close task authentication

**Comment by pelmegov** [comment]
I mean we have a PR with the same title and for the same jira, right, why do we need 2 similar PRs?

**Comment by saffchen** [comment]
> I mean we have a PR with the same title and for the same jira, right, why do we need 2 similar PRs?

Ok, closing this PR

**Pull request closed without merging**
